# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-10 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_session_app', '0002_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hogwarts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('house', models.CharField(max_length=45)),
                ('pet', models.CharField(max_length=45)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
